databases:
  - name: postgres
    databaseName: test_app_6ngu
    user: test_app
    plan: free

services:
  - type: web
    name: my_app
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
